name: "spacy_ner"
backend: "python"
max_batch_size: 16

input [
  {
    name: "text"
    data_type: TYPE_STRING
    dims: [ 1 ]
  }
]

output [
  {
    name: "entities"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]

instance_group [
  {
    kind: KIND_CPU
    count: 2
  }
]
